// ERD Schema definitions extracted from Firebase Firestore collections
// This file contains all collection schemas with their fields and types

export interface FieldDefinition {
  name: string
  type: string
  required: boolean
  description?: string
  isPrimaryKey?: boolean
  isForeignKey?: boolean
  references?: string
}

export interface CollectionSchema {
  name: string
  fields: FieldDefinition[]
  subcollections?: string[]
  description?: string
}

export interface Relationship {
  from: string
  to: string
  via: string
  type: 'one-to-one' | 'one-to-many' | 'many-to-one' | 'many-to-many'
}

export const erdSchema: CollectionSchema[] = [
  {
    name: 'students',
    description: 'Student documents with subcollections',
    fields: [
      { name: 'uid', type: 'string', required: true, isPrimaryKey: true },
      { name: 'email', type: 'string', required: true },
      { name: 'firstName', type: 'string', required: true },
      { name: 'middleName', type: 'string', required: false },
      { name: 'lastName', type: 'string', required: true },
      { name: 'nameExtension', type: 'string', required: false },
      { name: 'phoneNumber', type: 'string', required: true },
      { name: 'birthMonth', type: 'string', required: true },
      { name: 'birthDay', type: 'string', required: true },
      { name: 'birthYear', type: 'string', required: true },
      { name: 'gender', type: 'string', required: true },
      { name: 'civilStatus', type: 'string', required: true },
      { name: 'religion', type: 'string', required: false },
      { name: 'placeOfBirth', type: 'string', required: false },
      { name: 'citizenship', type: 'string', required: false },
      { name: 'streetName', type: 'string', required: true },
      { name: 'province', type: 'string', required: true },
      { name: 'municipality', type: 'string', required: true },
      { name: 'barangay', type: 'string', required: true },
      { name: 'zipCode', type: 'string', required: true },
      { name: 'guardianName', type: 'string', required: true },
      { name: 'guardianPhone', type: 'string', required: true },
      { name: 'guardianEmail', type: 'string', required: false },
      { name: 'guardianRelationship', type: 'string', required: true },
      { name: 'emergencyContact', type: 'string', required: false },
      { name: 'previousSchoolName', type: 'string', required: true },
      { name: 'previousSchoolType', type: 'string', required: true },
      { name: 'previousSchoolProvince', type: 'string', required: true },
      { name: 'previousSchoolMunicipality', type: 'string', required: true },
      { name: 'locationCodes', type: 'object', required: false },
      { name: 'locationCodes.province', type: 'string', required: false },
      { name: 'locationCodes.municipality', type: 'string', required: false },
      { name: 'locationCodes.barangay', type: 'string', required: false },
      {
        name: 'locationCodes.previousSchoolProvince',
        type: 'string',
        required: false,
      },
      {
        name: 'locationCodes.previousSchoolMunicipality',
        type: 'string',
        required: false,
      },
      { name: 'photoURL', type: 'string', required: false },
      {
        name: 'provider',
        type: "'email' | 'google' | 'magic-link'",
        required: true,
      },
      { name: 'studentId', type: 'string', required: false },
      { name: 'academicDataUsageAgreement', type: 'boolean', required: true },
      { name: 'documents', type: 'object', required: false },
      { name: 'documents.birthCertificate', type: 'object', required: false },
      {
        name: 'documents.certificateOfCompletion',
        type: 'object',
        required: false,
      },
      {
        name: 'documents.certificateOfGoodMoral',
        type: 'object',
        required: false,
      },
      { name: 'documents.form137', type: 'object', required: false },
      { name: 'documents.idPicture', type: 'object', required: false },
      { name: 'documents.reportCard', type: 'object', required: false },
      { name: 'documents.[key].fileFormat', type: 'string', required: false },
      { name: 'documents.[key].fileName', type: 'string', required: false },
      { name: 'documents.[key].fileSize', type: 'number', required: false },
      { name: 'documents.[key].fileType', type: 'string', required: false },
      { name: 'documents.[key].fileUrl', type: 'string', required: false },
      { name: 'documents.[key].status', type: 'string', required: false },
      {
        name: 'documents.[key].uploadDate',
        type: 'string (ISO)',
        required: false,
      },
      {
        name: 'documents.[key].uploadedAt',
        type: 'string (ISO)',
        required: false,
      },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
      { name: 'lastLoginAt', type: 'string (ISO)', required: true },
    ],
    subcollections: ['enrollment', 'studentGrades'],
  },
  {
    name: 'students/{userId}/enrollment',
    description: 'Enrollment subcollection under students',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      {
        name: 'userId',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'students.id',
      },
      { name: 'personalInfo', type: 'object', required: true },
      { name: 'personalInfo.firstName', type: 'string', required: true },
      { name: 'personalInfo.middleName', type: 'string', required: false },
      { name: 'personalInfo.lastName', type: 'string', required: true },
      { name: 'personalInfo.nameExtension', type: 'string', required: false },
      { name: 'personalInfo.email', type: 'string', required: true },
      { name: 'personalInfo.phone', type: 'string', required: true },
      { name: 'personalInfo.birthDay', type: 'string', required: true },
      { name: 'personalInfo.birthMonth', type: 'string', required: true },
      { name: 'personalInfo.birthYear', type: 'string', required: true },
      { name: 'personalInfo.citizenship', type: 'string', required: true },
      { name: 'personalInfo.civilStatus', type: 'string', required: true },
      { name: 'personalInfo.gender', type: 'string', required: true },
      { name: 'personalInfo.placeOfBirth', type: 'string', required: true },
      { name: 'personalInfo.religion', type: 'string', required: false },
      { name: 'enrollmentInfo', type: 'object', required: true },
      { name: 'enrollmentInfo.gradeLevel', type: 'string', required: false },
      { name: 'enrollmentInfo.department', type: 'string', required: false },
      { name: 'enrollmentInfo.strand', type: 'string', required: false },
      {
        name: 'enrollmentInfo.semester',
        type: "'first-sem' | 'second-sem'",
        required: false,
      },
      {
        name: 'enrollmentInfo.courseId',
        type: 'string',
        required: false,
        isForeignKey: true,
        references: 'courses.code',
      },
      { name: 'enrollmentInfo.courseCode', type: 'string', required: false },
      { name: 'enrollmentInfo.courseName', type: 'string', required: false },
      { name: 'enrollmentInfo.yearLevel', type: 'number', required: false },
      { name: 'enrollmentInfo.schoolYear', type: 'string', required: true },
      {
        name: 'enrollmentInfo.enrollmentDate',
        type: 'string (ISO)',
        required: true,
      },
      { name: 'enrollmentInfo.status', type: 'string', required: true },
      { name: 'enrollmentInfo.orNumber', type: 'string', required: false },
      { name: 'enrollmentInfo.scholarship', type: 'string', required: false },
      { name: 'enrollmentInfo.studentId', type: 'string', required: false },
      {
        name: 'enrollmentInfo.sectionId',
        type: 'string',
        required: false,
        isForeignKey: true,
        references: 'sections.id',
      },
      {
        name: 'enrollmentInfo.studentType',
        type: "'regular' | 'irregular'",
        required: false,
      },
      {
        name: 'enrollmentInfo.level',
        type: "'high-school' | 'college'",
        required: true,
      },
      { name: 'selectedSubjects', type: 'string[]', required: false },
      { name: 'documents', type: 'object', required: false },
      { name: 'submittedAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
    ],
  },
  {
    name: 'students/{userId}/studentGrades',
    description: 'Student grades subcollection',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      { name: 'studentName', type: 'string', required: false },
      { name: 'studentSection', type: 'string', required: false },
      { name: 'studentLevel', type: 'string', required: false },
      { name: 'studentSemester', type: 'string', required: false },
      {
        name: '[subjectId]',
        type: 'object',
        required: false,
        description: 'Dynamic field per subject',
      },
      { name: '[subjectId].subjectName', type: 'string', required: false },
      { name: '[subjectId].period1', type: 'number | null', required: false },
      { name: '[subjectId].period2', type: 'number | null', required: false },
      { name: '[subjectId].period3', type: 'number | null', required: false },
      { name: '[subjectId].period4', type: 'number | null', required: false },
      { name: 'createdAt', type: 'string (ISO)', required: false },
      { name: 'updatedAt', type: 'string (ISO)', required: false },
    ],
  },
  {
    name: 'teachers',
    description: 'Teacher information',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      { name: 'firstName', type: 'string', required: true },
      { name: 'middleName', type: 'string', required: false },
      { name: 'lastName', type: 'string', required: true },
      { name: 'extension', type: 'string', required: false },
      { name: 'email', type: 'string', required: true },
      { name: 'phone', type: 'string', required: true },
      { name: 'uid', type: 'string', required: false },
      { name: 'status', type: "'active' | 'inactive'", required: false },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
      {
        name: 'createdBy',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'registrars.uid',
      },
    ],
  },
  {
    name: 'registrars',
    description: 'Registrar information',
    fields: [
      { name: 'uid', type: 'string', required: true, isPrimaryKey: true },
      { name: 'email', type: 'string', required: true },
      { name: 'firstName', type: 'string', required: true },
      { name: 'lastName', type: 'string', required: true },
      { name: 'middleName', type: 'string', required: false },
      { name: 'nameExtension', type: 'string', required: false },
      { name: 'birthday', type: 'string', required: false },
      { name: 'role', type: "'registrar'", required: true },
      { name: 'photoURL', type: 'string', required: false },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
      { name: 'lastLoginAt', type: 'string (ISO)', required: true },
    ],
  },
  {
    name: 'grades',
    description: 'Grade level definitions (JHS/SHS)',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      { name: 'gradeLevel', type: 'number', required: true },
      { name: 'department', type: "'JHS' | 'SHS' | 'COLLEGE'", required: true },
      { name: 'strand', type: 'string', required: false },
      { name: 'description', type: 'string', required: true },
      { name: 'color', type: 'GradeColor', required: true },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
      {
        name: 'createdBy',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'registrars.uid',
      },
    ],
  },
  {
    name: 'sections',
    description: 'Section definitions',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      {
        name: 'gradeId',
        type: 'string',
        required: false,
        isForeignKey: true,
        references: 'grades.id',
      },
      {
        name: 'courseId',
        type: 'string',
        required: false,
        isForeignKey: true,
        references: 'courses.code',
      },
      { name: 'sectionName', type: 'string', required: true },
      { name: 'grade', type: 'string', required: true },
      { name: 'department', type: "'JHS' | 'SHS' | 'COLLEGE'", required: true },
      {
        name: 'rank',
        type: "'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H'",
        required: true,
      },
      { name: 'description', type: 'string', required: true },
      { name: 'students', type: 'string[]', required: false },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
      {
        name: 'createdBy',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'registrars.uid',
      },
    ],
  },
  {
    name: 'courses',
    description: 'College course definitions',
    fields: [
      { name: 'code', type: 'string', required: true, isPrimaryKey: true },
      { name: 'name', type: 'string', required: true },
      { name: 'description', type: 'string', required: true },
      { name: 'color', type: 'CourseColor', required: true },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
      {
        name: 'createdBy',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'registrars.uid',
      },
    ],
  },
  {
    name: 'subjects',
    description: 'Subject/course definitions',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      { name: 'code', type: 'string', required: true },
      { name: 'name', type: 'string', required: true },
      { name: 'description', type: 'string', required: true },
      { name: 'gradeLevels', type: 'number[]', required: false },
      { name: 'gradeIds', type: 'string[]', required: false },
      {
        name: 'gradeLevel',
        type: 'number',
        required: false,
        description: 'Legacy field',
      },
      { name: 'courseCodes', type: 'string[]', required: false },
      { name: 'courseSelections', type: 'object[]', required: false },
      { name: 'color', type: 'SubjectColor', required: true },
      { name: 'lectureUnits', type: 'number', required: true },
      { name: 'labUnits', type: 'number', required: true },
      { name: 'totalUnits', type: 'number', required: true },
      { name: 'prerequisites', type: 'string[]', required: false },
      { name: 'postrequisites', type: 'string[]', required: false },
      { name: 'teacherAssignments', type: 'object', required: false },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
      {
        name: 'createdBy',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'registrars.uid',
      },
    ],
  },
  {
    name: 'subjectSets',
    description: 'Subject set groupings',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      { name: 'name', type: 'string', required: true },
      { name: 'description', type: 'string', required: true },
      {
        name: 'subjects',
        type: 'string[]',
        required: true,
        description: 'Array of subject IDs',
      },
      { name: 'gradeLevel', type: 'number', required: true },
      { name: 'color', type: 'SubjectColor', required: true },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
      {
        name: 'createdBy',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'registrars.uid',
      },
    ],
  },
  {
    name: 'subjectAssignments',
    description: 'Subject assignments to grades/courses',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      { name: 'level', type: "'high-school' | 'college'", required: true },
      {
        name: 'gradeId',
        type: 'string',
        required: false,
        isForeignKey: true,
        references: 'grades.id',
      },
      { name: 'gradeLevel', type: 'number', required: false },
      {
        name: 'courseCode',
        type: 'string',
        required: false,
        isForeignKey: true,
        references: 'courses.code',
      },
      { name: 'courseName', type: 'string', required: false },
      { name: 'yearLevel', type: 'number', required: false },
      { name: 'semester', type: "'first-sem' | 'second-sem'", required: false },
      { name: 'strand', type: 'string', required: false },
      {
        name: 'subjectSetId',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'subjectSets.id',
      },
      {
        name: 'registrarUid',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'registrars.uid',
      },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
    ],
  },
  {
    name: 'enrollments',
    description: 'Top-level enrollment documents',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      {
        name: 'userId',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'students.id',
      },
      { name: 'ayCode', type: 'string', required: true },
      { name: 'semester', type: 'string', required: false },
      {
        name: 'enrollmentData',
        type: 'object',
        required: true,
        description: 'Same structure as students/{userId}/enrollment',
      },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
    ],
  },
  {
    name: 'events',
    description: 'Calendar events',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      { name: 'title', type: 'string', required: true },
      { name: 'description', type: 'string', required: true },
      { name: 'startDate', type: 'string (ISO)', required: true },
      { name: 'endDate', type: 'string (ISO) | null', required: false },
      { name: 'color', type: 'EventColor', required: true },
      { name: 'icon', type: 'string', required: true },
      { name: 'visibleAudience', type: 'EventLevel[]', required: true },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
      {
        name: 'createdBy',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'registrars.uid',
      },
    ],
  },
  {
    name: 'registrarTasks',
    description: 'Registrar task management',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      {
        name: 'registrarUid',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'registrars.uid',
      },
      { name: 'title', type: 'string', required: true },
      { name: 'description', type: 'string', required: false },
      { name: 'status', type: "'pending' | 'completed'", required: true },
      { name: 'priority', type: "'low' | 'medium' | 'high'", required: false },
      { name: 'dueDate', type: 'string (ISO)', required: false },
      { name: 'color', type: 'TaskColor', required: true },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
    ],
  },
  {
    name: 'chats',
    description: 'Chat conversations',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      { name: 'participants', type: 'string[]', required: true },
      { name: 'lastMessage', type: 'string', required: false },
      { name: 'lastMessageAt', type: 'string (ISO)', required: false },
      { name: 'createdAt', type: 'string (ISO)', required: true },
      { name: 'updatedAt', type: 'string (ISO)', required: true },
    ],
    subcollections: ['messages'],
  },
  {
    name: 'chats/{chatId}/messages',
    description: 'Messages subcollection under chats',
    fields: [
      { name: 'id', type: 'string', required: true, isPrimaryKey: true },
      {
        name: 'chatId',
        type: 'string',
        required: true,
        isForeignKey: true,
        references: 'chats.id',
      },
      { name: 'senderId', type: 'string', required: true },
      { name: 'content', type: 'string', required: true },
      { name: 'type', type: "'text' | 'file' | 'image'", required: true },
      { name: 'fileUrl', type: 'string', required: false },
      { name: 'fileName', type: 'string', required: false },
      { name: 'fileSize', type: 'number', required: false },
      { name: 'readBy', type: 'object', required: true },
      { name: 'createdAt', type: 'string (ISO)', required: true },
    ],
  },
  {
    name: 'config',
    description: 'System configuration (single document)',
    fields: [
      {
        name: 'id',
        type: 'string',
        required: true,
        isPrimaryKey: true,
        description: 'Document ID: "system"',
      },
      { name: 'ayCode', type: 'string', required: false },
      { name: 'currentAY', type: 'string', required: false },
      { name: 'academicYear', type: 'string', required: false },
      { name: 'AYCode', type: 'string', required: false },
      { name: 'activeAY', type: 'string', required: false },
      { name: 'AY', type: 'string', required: false },
      { name: 'semester', type: 'string', required: false },
      { name: 'enrollmentStartPeriodHS', type: 'string', required: false },
      { name: 'enrollmentEndPeriodHS', type: 'string', required: false },
      { name: 'enrollmentStartPeriodCollege', type: 'string', required: false },
      { name: 'enrollmentEndPeriodCollege', type: 'string', required: false },
      { name: 'latestId', type: 'string', required: false },
      { name: 'updatedAt', type: 'string (ISO)', required: false },
    ],
  },
]

export const relationships: Relationship[] = [
  { from: 'students', to: 'enrollments', via: 'userId', type: 'one-to-many' },
  {
    from: 'enrollments',
    to: 'sections',
    via: 'enrollmentInfo.sectionId',
    type: 'many-to-one',
  },
  { from: 'sections', to: 'grades', via: 'gradeId', type: 'many-to-one' },
  { from: 'sections', to: 'courses', via: 'courseId', type: 'many-to-one' },
  {
    from: 'enrollments',
    to: 'courses',
    via: 'enrollmentInfo.courseId',
    type: 'many-to-one',
  },
  {
    from: 'subjectAssignments',
    to: 'subjectSets',
    via: 'subjectSetId',
    type: 'many-to-one',
  },
  {
    from: 'subjectSets',
    to: 'subjects',
    via: 'subjects[]',
    type: 'many-to-many',
  },
  { from: 'chats', to: 'messages', via: 'chatId', type: 'one-to-many' },
  {
    from: 'registrarTasks',
    to: 'registrars',
    via: 'registrarUid',
    type: 'many-to-one',
  },
  { from: 'teachers', to: 'registrars', via: 'createdBy', type: 'many-to-one' },
  { from: 'grades', to: 'registrars', via: 'createdBy', type: 'many-to-one' },
  { from: 'sections', to: 'registrars', via: 'createdBy', type: 'many-to-one' },
  { from: 'courses', to: 'registrars', via: 'createdBy', type: 'many-to-one' },
  { from: 'subjects', to: 'registrars', via: 'createdBy', type: 'many-to-one' },
  {
    from: 'subjectSets',
    to: 'registrars',
    via: 'createdBy',
    type: 'many-to-one',
  },
  {
    from: 'subjectAssignments',
    to: 'registrars',
    via: 'registrarUid',
    type: 'many-to-one',
  },
  { from: 'events', to: 'registrars', via: 'createdBy', type: 'many-to-one' },
]
